name: Go

on:
  pull_request:
    branches: [ "main" ]
  # Manual trigger for debugging or reruns
  workflow_dispatch: {}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25.5']
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: services/gateway/go.sum

      - name: Build
        working-directory: services/gateway
        run: go build -v ./...

      - name: Check
        working-directory: services/gateway
        run: |
          go vet ./...
          gofmt -s -w .
          git diff --exit-code

      - name: Test
        working-directory: services/gateway
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        
      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: services/gateway